version: '3'
services:
  opensearch-node3:
    image: opensearchproject/opensearch:1.3.2
    container_name: opensearch-node3
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node3
      - discovery.seed_providers=file
      # - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data3:/usr/share/opensearch/data
      - ./unicast_hosts.txt:/usr/share/opensearch/config/unicast_hosts.txt
    ports:
      - 9203:9200
    networks:
      - opensearch-net


volumes:
  opensearch-data3:

networks:
  opensearch-net:
