version: '3'
services:
  ops-data-2:
    image: opensearchproject/opensearch:2.0.0
    container_name: ops-data-2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=ops-data-2
      # - discovery.seed_providers=file
      - bootstrap.memory_lock=true
      - node.roles=data,ingest
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ops-data-2:/usr/share/opensearch/data
      - ./unicast_hosts.txt:/usr/share/opensearch/config/unicast_hosts.txt
    networks:
      - opensearch-net
    ports:
      - 9205:9200

volumes:
  ops-data-2:

networks:
  opensearch-net:
