version: '3'
services:
  ops-master-2:
    image: opensearchproject/opensearch:2.0.0
    container_name: ops-master-2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=ops-master-2
      # - discovery.seed_providers=file
      - cluster.initial_master_nodes=ops-master-1,ops-master-2,ops-master-3
      - bootstrap.memory_lock=true
      - node.roles=cluster_manager
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ops-master-2:/usr/share/opensearch/data
      # - ./unicast_hosts.txt:/usr/share/opensearch/config/unicast_hosts.txt
    # ports:
    #   - 9202:9200
    networks:
      - opensearch-net
  

volumes:
  ops-master-2:

networks:
  opensearch-net:
