version: '3'
services:
  opensearch-node4:
    image: opensearchproject/opensearch:1.3.2
    container_name: opensearch-node4
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node4
      # - discovery.seed_providers=file
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data4:/usr/share/opensearch/data
      - ./unicast_hosts.txt:/usr/share/opensearch/config/unicast_hosts.txt
    networks:
      - opensearch-net
    ports:
      - 9204:9200

volumes:
  opensearch-data4:

networks:
  opensearch-net:
